### ISSUE TITLE
Color contrast using dark theme

### ISSUE THREAD

**Issue by goblej216** [benwinding/vuex-trace#1]
Love the library man, it helps out a ton being able to track actions.  One request I have.. while using a dark theme for my dev tools the color contrasts on the actions and mutations entries are super rough on the eyes lol.  Maybe it's the bold text or just the background color, but it's tough to look at after a while.

I've attached a screenshot it sadly doesn't really do it justice.
![Screen Shot 2020-10-29 at 1 02 23 PM](https://user-images.githubusercontent.com/63607028/97608341-9b16c580-19e8-11eb-90b1-9576c0f26e79.png)

**Comment by benwinding** [comment]
Hi @goblej216, Glad it's useful for you!

This should be fixed now, checking if the browser is in "dark mode"
![image](https://user-images.githubusercontent.com/11782590/97655058-24df9500-1ab4-11eb-93f5-ef969b84f33c.png)
